#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /test
    controller: noFlash\Owl\Controller\DefaultController::test

publish:
    path: /publish
    controller: noFlash\Owl\Controller\PublisherController::publish
